/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorial: [
    {
      type: "category",
      label: "指南",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial",
        },
      ],
    },
    {
      type: "category",
      label: "进阶",
      items: [
        {
          type: "autogenerated",
          dirName: "advanced",
        },
      ],
    },
    {
      type: "category",
      label: "开发者",
      items: [
        {
          type: "autogenerated",
          dirName: "developer",
        },
      ],
    },
  ],
};

export default sidebars;
